### ISSUE TITLE
Flying with a single real crazyflie (Using LPS) - Could not find param /commander/enHighLevel

### ISSUE THREAD

**Issue by tugayalperen** [wuwushrek/sim_cf#1]
Hi there,
As I mentioned in the Bitcraze forum (https://forum.bitcraze.io/viewtopic.php?f=2&t=2929&start=20), we have our LPS system with 8 nodes is installed. I have tested their functionality with cflib, in addition to crazyflie-ros and they are working as they supposed to. Since we are working with your version on SITL for a while, it is really exciting to have a chance to apply our work to real systems.
When I try to do that, I successfully start the server and add a crazyflie under /cf1 namespace with corresponding URI, I can even echo the pose topic. Unfortunately after that, I can not go further with test_high_level.py, having an error saying that;

[ERROR] [1535978471.370209333]: [/cf1] Could not find param /commander/enHighLevel

In addition, there is a constant low link quality error which I do not face with in other alternatives (cflib and crazyflie-ros). One think I am suspecting is that the firmware. In our cfs, the official release of crazyflie-firmware (2018.01) is uploaded. Should we use the source code in your workspace for the firmware to be uploaded to cfs?

Did you ever tried real cfs+LPS combination and if you do, which firmwares were uploaded? At least, do you have any suggestion for the problems we are facing with?

Thanks in advance, 
![screenshot from 2018-09-03 16-18-06](https://user-images.githubusercontent.com/32046508/44989333-2d9cb500-af96-11e8-9a2b-deff41399a81.png)

**Comment by wuwushrek** [comment]
@tugayalperen 
Hi and sorry for the late reply.
YES I already test my code with real quadcopter  (at least the test_high_level.py script ) and it worked well. Usually what I do is that I upload the latest version of crazyflie source code and flash it into my crazyflie. But I still use the crazyflie_gazebo package for high level command.
Are you using the multi-uav-final branch ?
Can you try rosparam list in order to see in which namespace the params are ?

**Comment by tugayalperen** [comment]
Hi,
Fortunately, I have already overcome this issue, as you guess the problem was about I am using firmware release 2018.01, not the final version. Although it is not related to this issue, we have another type of problem right now, as I mentioned in the forum (https://forum.bitcraze.io/viewtopic.php?f=16&t=3164), thanks for your help.

Before closing, one last question, is it possible to use same configuration with your workspace, for multiple cf tests right, of course with a decent launch file for crazyflie_add.launch ( I mean the real testing with LPS). Something like the attachment (and of course appropriate namespace calls in high level commands).
![screenshot from 2018-09-07 10-11-55]
(https://user-images.githubusercontent.com/32046508/45204027-b6616c80-b286-11e8-90e9-8ea5429ba391.png)

**Comment by wuwushrek** [comment]
Sorry for the very late response. This should be doable now. I made me more modular in order to use directly crazyflie_ros launch and scripts. It should also be faster.
